// Generated by tools/build-versions.mjs — do not edit.
// A classic script too, so the service worker can importScripts() it.
self.DWELL_VERSIONS = [
  {
    "id": "bsb",
    "abbr": "BSB",
    "name": "Berean Standard Bible",
    "note": "Public domain",
    "public": true
  }
];
