// Writes js/canon-data.js — book names and verses per chapter, the verse grid
// every version is fitted to — from a scrollmapper-format Bible JSON. The
// grid is fixed now (stored verse ids depend on it); text comes from
// tools/build-versions.mjs.
// usage: node tools/build-data.mjs <source.json>
import fs from 'node:fs';
import path from 'node:path';

const [src, id = 'bsb'] = process.argv.slice(2);
if (!src) { console.error('usage: build-data.mjs <source.json> <id>'); process.exit(1); }

const NAMES = [
  ['Genesis','Gen'],['Exodus','Exod'],['Leviticus','Lev'],['Numbers','Num'],['Deuteronomy','Deut'],
  ['Joshua','Josh'],['Judges','Judg'],['Ruth','Ruth'],['1 Samuel','1Sam'],['2 Samuel','2Sam'],
  ['1 Kings','1Kgs'],['2 Kings','2Kgs'],['1 Chronicles','1Chr'],['2 Chronicles','2Chr'],['Ezra','Ezra'],
  ['Nehemiah','Neh'],['Esther','Esth'],['Job','Job'],['Psalms','Ps'],['Proverbs','Prov'],
  ['Ecclesiastes','Eccl'],['Song of Songs','Song'],['Isaiah','Isa'],['Jeremiah','Jer'],['Lamentations','Lam'],
  ['Ezekiel','Ezek'],['Daniel','Dan'],['Hosea','Hos'],['Joel','Joel'],['Amos','Amos'],
  ['Obadiah','Obad'],['Jonah','Jonah'],['Micah','Mic'],['Nahum','Nah'],['Habakkuk','Hab'],
  ['Zephaniah','Zeph'],['Haggai','Hag'],['Zechariah','Zech'],['Malachi','Mal'],
  ['Matthew','Matt'],['Mark','Mark'],['Luke','Luke'],['John','John'],['Acts','Acts'],
  ['Romans','Rom'],['1 Corinthians','1Cor'],['2 Corinthians','2Cor'],['Galatians','Gal'],['Ephesians','Eph'],
  ['Philippians','Phil'],['Colossians','Col'],['1 Thessalonians','1Thess'],['2 Thessalonians','2Thess'],
  ['1 Timothy','1Tim'],['2 Timothy','2Tim'],['Titus','Titus'],['Philemon','Phlm'],['Hebrews','Heb'],
  ['James','Jas'],['1 Peter','1Pet'],['2 Peter','2Pet'],['1 John','1John'],['2 John','2John'],
  ['3 John','3John'],['Jude','Jude'],['Revelation','Rev'],
];

let raw = fs.readFileSync(src, 'utf8');
if (raw.charCodeAt(0) === 0xfeff) raw = raw.slice(1);
const data = JSON.parse(raw);
if (data.books.length !== 66) throw new Error(`expected 66 books, got ${data.books.length}`);

const books = [];
let total = 0;
data.books.forEach((b, i) => {
  const chapters = b.chapters.map(c => c.verses.map(v => v.text.trim()));
  chapters.forEach((c, ci) => {
    const nums = b.chapters[ci].verses.map(v => v.verse);
    nums.forEach((n, k) => { if (n !== k + 1) throw new Error(`${b.name} ${ci + 1}: verse ${n} at ${k + 1}`); });
  });
  total += chapters.reduce((s, c) => s + c.length, 0);
  books.push({ name: NAMES[i][0], abbr: NAMES[i][1], verses: chapters.map(c => c.length) });
});
if (total !== 31102) throw new Error(`expected 31102 verses, got ${total}`);

const canon = `// Generated by tools/build-data.mjs — do not edit.
export const BOOKS = ${JSON.stringify(books)};
`;
fs.writeFileSync(path.resolve('js', 'canon-data.js'), canon);
console.log(`wrote ${books.length} books, ${total} verses to js/canon-data.js`);
